#!/bin/bash

botoption=$1
imagename=$2

if [ $botoption == "production-test" ]
then
	cd loopback_chatbot && npm run prod && cd .. && docker-compose -f docker-compose.yml -f docker-compose.prod.yml up 
elif [ $botoption == "production-deploy" ]
then
	docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
elif [ $botoption == "development" ]
then
	cd loopback_chatbot && npm run dev && cd .. && docker-compose up 
elif [ $botoption == "refactor" ]
then
	docker-compose down && docker rmi $imagename && cd loopback_chatbot && npm run dev && cd .. && docker-compose up
elif [ $botoption == "teardown" ]
then
    docker-compose down && docker rmi $imagename
fi

exit 0
