#!/bin/bash

botoption=$1
imagename=$2

if [ $botoption == "production" ]
then
	docker-compose -f docker-compose.yml -f docker-compose.prod.yml up 
elif [ $botoption == "development" ]
then
	docker-compose up 
elif [ $botoption == "refactor" ]
then
	docker-compose down && docker rmi $imagename && cd loopback_chatbot && npm run build && cd .. && docker-compose up
elif [ $botoption == "teardown" ]
then
    docker-compose down && docker rmi $imagename
fi

exit 0
